version: '3.8'
services:
  mysql:
    image: mysql:8.0
    volumes:
      - mysql_volum_fiapsmart:/var/lib/mysql
    ports:
      - 53306:3306
    environment:
      - MYSQL_DATABASE=fiapsmart
      - MYSQL_USER=fiap
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
volumes:
  mysql_volum_fiapsmart: